///// Project module/////

module.exports = {
  MIN_PROGRESS: 0,
  MAX_PROGRESS: 100,

  PROJECT_NAME_MIN_LENGTH: 10,
  PROJECT_NAME_MAX_LENGTH: 100,

  CLIENT_MIN_LENGTH: 10,
  CLIENT_MAX_LENGTH: 75,

  MANAGER_MIN_LENGTH: 5,
  MANAGER_MAX_LENGTH: 75,

  DESCRIPTION_MAX_LENGTH: 300,
  
  OVERVIEW_MAX_LENGTH: 3000,

  NOTES_MAX_LENGTH:5000
};
